app: forgejo-with-mysql
description: "Forgejo is a self-hosted lightweight software forge. Easy to install and low maintenance, it just does the job."
icon: https://raw.githubusercontent.com/jekyo/templates/main/forgejo-with-mysql/logo.svg
inputs:
  DOMAIN:
    kind: domain
    prompt: Domain for Forgejo
  MYSQL_PASSWORD:
    kind: secret
  MYSQL_ROOT_PASSWORD:
    kind: secret
  MIGRATIONS_ALLOWED_DOMAINS:
    kind: string
    default: ""
    required: false
    prompt: Allowed domains for repository migrations
  DATA_SIZE:
    kind: size
    default: 10Gi
    prompt: Storage size
services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:8
    env:
      FORGEJO__server__ROOT_URL: https://${DOMAIN}
      FORGEJO__migrations__ALLOWED_DOMAINS: ${MIGRATIONS_ALLOWED_DOMAINS}
      FORGEJO__migrations__ALLOW_LOCALNETWORKS: "false"
      USER_UID: "1000"
      USER_GID: "1000"
      FORGEJO__database__DB_TYPE: mysql
      FORGEJO__database__HOST: mysql
      FORGEJO__database__NAME: forgejo
      FORGEJO__database__USER: forgejo
      FORGEJO__database__PASSWD: ${MYSQL_PASSWORD}
    port: 3000
    http:
      domain: ${DOMAIN}
    health:
      path: /
      port: 3000
    volumes:
      data:
        path: /data
        subpath: forgejo
  mysql:
    image: mysql:8
    env:
      MYSQL_USER: forgejo
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: forgejo
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    port: 3306
    health:
      command: ["mysqladmin", "ping", "-h", "127.0.0.1"]
    volumes:
      data:
        path: /var/lib/mysql
        subpath: mysql
volumes:
  data:
    size: ${DATA_SIZE}
