app: seafile
description: Seafile: open source cloud storage system for file sync, share and document collaboration
icon: https://raw.githubusercontent.com/jekyo/templates/main/seafile/logo.svg
inputs:
  DOMAIN:
    kind: domain
    prompt: Domain for Seafile
  MYSQL_ROOT_PASSWORD:
    kind: secret
  MYSQL_PASSWORD:
    kind: secret
  ADMIN_EMAIL:
    kind: string
    default: admin@example.com
    required: false
    prompt: Initial admin email
  ADMIN_PASSWORD:
    kind: secret
  JWT_PRIVATE_KEY:
    kind: secret
  DATA_SIZE:
    kind: size
    default: 20Gi
    prompt: Storage size
services:
  seafile:
    image: seafileltd/seafile-mc:12.0-latest
    env:
      SEAFILE_SERVER_HOSTNAME: ${DOMAIN}
      DB_HOST: mariadb
      DB_PORT: "3306"
      DB_ROOT_PASSWD: ${MYSQL_ROOT_PASSWORD}
      DB_USER: seafile
      DB_PASSWORD: ${MYSQL_PASSWORD}
      SEAFILE_MYSQL_DB_CCNET_DB_NAME: ccnet_db
      SEAFILE_MYSQL_DB_SEAFILE_DB_NAME: seafile_db
      SEAFILE_MYSQL_DB_SEAHUB_DB_NAME: seahub_db
      TIME_ZONE: UTC
      INIT_SEAFILE_ADMIN_EMAIL: ${ADMIN_EMAIL}
      INIT_SEAFILE_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SEAFILE_SERVER_PROTOCOL: https
      SITE_ROOT: /
      NON_ROOT: "false"
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      SEAFILE_LOG_TO_STDOUT: "true"
      FILE_SERVER_ROOT: https://${DOMAIN}/seafhttp
    port: 80
    http:
      domain: ${DOMAIN}
    health:
      path: /api2/ping
      port: 80
    volumes:
      data:
        path: /shared
        subpath: seafile
  mariadb:
    image: mariadb:11
    env:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: seafile
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: seafile-db
    port: 3306
    health:
      command: ["healthcheck.sh", "--connect", "--innodb_initialized"]
    volumes:
      data:
        path: /var/lib/mysql
        subpath: mariadb
  memcached:
    image: memcached:latest
    command: ["memcached", "-m", "256"]
    port: 11211
    health:
      command: ["sh", "-c", "bash -c 'echo version | (exec 3<>/dev/tcp/localhost/11211; cat >&3; timeout 0.5 cat <&3; exec 3<&-)'"]
volumes:
  data:
    size: ${DATA_SIZE}
