app: litequeen
description: Lite Queen is an open-source SQLite database management software that runs on your server.
icon: https://raw.githubusercontent.com/jekyo/templates/main/litequeen/logo.svg
inputs:
  DOMAIN:
    kind: domain
    prompt: Domain for Lite Queen
  DATA_SIZE:
    kind: size
    default: 2Gi
    prompt: Storage size
services:
  litequeen:
    image: kivsegrob/lite-queen:latest
    port: 8000
    http:
      domain: ${DOMAIN}
    health:
      command: ["sh", "-c", "bash -c ':> /dev/tcp/127.0.0.1/8000' || exit 1"]
    volumes:
      data:
        path: /home/litequeen/data
      databases:
        path: /srv
volumes:
  data:
    size: 1Gi
  databases:
    size: ${DATA_SIZE}
