app: gotenberg
description: Gotenberg is a Docker-powered stateless API for PDF files.
icon: https://raw.githubusercontent.com/jekyo/templates/main/gotenberg/logo.png
inputs:
  DOMAIN:
    kind: domain
    prompt: Domain for Gotenberg
  GOTENBERG_PASSWORD:
    kind: secret
services:
  gotenberg:
    image: gotenberg/gotenberg:latest
    command: ["gotenberg"]
    args:
      - --api-enable-basic-auth
      - --api-disable-health-check-logging
    env:
      GOTENBERG_API_BASIC_AUTH_USERNAME: gotenberg
      GOTENBERG_API_BASIC_AUTH_PASSWORD: ${GOTENBERG_PASSWORD}
    port: 3000
    http:
      domain: ${DOMAIN}
    health:
      path: /health
      port: 3000
