app: nextcloud
description: NextCloud is a self-hosted, open-source platform that provides file storage, collaboration, and communication tools for seamless data management.
icon: https://raw.githubusercontent.com/jekyo/templates/main/nextcloud/logo.svg
inputs:
  DOMAIN:
    kind: domain
    prompt: Domain for your Nextcloud
  TZ:
    kind: string
    default: Europe/Madrid
    required: false
    prompt: Timezone
  DATA_SIZE:
    kind: size
    default: 20Gi
    prompt: Storage size for files
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: ${TZ}
    port: 80
    http:
      domain: ${DOMAIN}
    health:
      path: /status.php
      port: 80
    volumes:
      config: /config
      data: /data
volumes:
  data:
    size: ${DATA_SIZE}
  config:
    size: 2Gi
