app: cloudbeaver
description: CloudBeaver is a lightweight web application designed for comprehensive data management.
icon: https://raw.githubusercontent.com/jekyo/templates/main/cloudbeaver/logo.svg
inputs:
  DOMAIN:
    kind: domain
    prompt: Domain for CloudBeaver
  DATA_SIZE:
    kind: size
    default: 2Gi
    prompt: Storage size
services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:24
    port: 8978
    http:
      domain: ${DOMAIN}
    health:
      path: /
      port: 8978
    volumes:
      data:
        path: /opt/cloudbeaver/workspace
volumes:
  data:
    size: ${DATA_SIZE}
