app: uptime-kuma-with-mysql
description: Uptime Kuma is a monitoring tool for tracking the status and performance of your applications in real-time.
icon: https://raw.githubusercontent.com/jekyo/templates/main/uptime-kuma-with-mysql/logo.svg
inputs:
  DOMAIN:
    kind: domain
    prompt: Domain for Uptime Kuma
  MYSQL_PASSWORD:
    kind: secret
  MYSQL_ROOT_PASSWORD:
    kind: secret
  TZ:
    kind: string
    default: Etc/UTC
    required: false
    prompt: Timezone
  DATA_SIZE:
    kind: size
    default: 2Gi
    prompt: Storage size
services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    env:
      TZ: ${TZ}
    port: 3001
    http:
      domain: ${DOMAIN}
    health:
      command: ["sh", "-c", "extra/healthcheck"]
    volumes:
      data:
        path: /app/data
        subpath: uptime-kuma
  mysql:
    image: mysql:8
    env:
      MYSQL_USER: uptimekuma
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: uptime-kuma-db
    port: 3306
    health:
      command: ["mysqladmin", "ping", "-h", "127.0.0.1"]
    volumes:
      data:
        path: /var/lib/mysql
        subpath: mysql
volumes:
  data:
    size: ${DATA_SIZE}
