app: logto
description: A comprehensive identity solution covering both the front and backend, complete with pre-built infrastructure and enterprise-grade solutions.
icon: https://raw.githubusercontent.com/jekyo/templates/main/logto/logo.svg
inputs:
  DOMAIN:
    kind: domain
    prompt: Domain for Logto
  POSTGRES_PASSWORD:
    kind: secret
  DATA_SIZE:
    kind: size
    default: 2Gi
    prompt: Storage size
services:
  logto:
    image: svhd/logto:latest
    command: ["sh", "-c", "npm run cli db seed -- --swe && npm run alteration deploy latest && npm start"]
    env:
      TRUST_PROXY_HEADER: "1"
      DB_URL: postgres://logto:${POSTGRES_PASSWORD}@postgres:5432/logto
      ENDPOINT: https://${DOMAIN}
    ports: [3001, 3002]
    http:
      domain: ${DOMAIN}
  postgres:
    image: postgres:14-alpine
    env:
      POSTGRES_USER: logto
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: logto
    port: 5432
    health:
      command: ["pg_isready", "-U", "logto", "-d", "logto"]
    volumes:
      data:
        path: /var/lib/postgresql/data
        subpath: postgres
volumes:
  data:
    size: ${DATA_SIZE}
